"""Generate the TikZ source of the true residue graph G_j modulo 2^j.

The graph is read directly from collatz.invariants.transition_graph_mod2j —
the same construction consumed by Karp's algorithm (paper Sect. "The
obstruction as a graph problem") — so the figure in the manuscript is a
verification output, not a hand-drawing.

Usage (from the repository root):

    python3 paper/make_residue_graph_figure.py [j]

Writes paper/residue_graph_j{j}.tex (default j = 4), which main.tex inputs.
The output is deterministic: rerunning the script reproduces the file
byte-for-byte.
"""

from __future__ import annotations

import math
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), os.pardir))

from collatz.invariants import transition_graph_mod2j  # noqa: E402

RADIUS_CM = 3.4


def tikz_residue_graph(j: int) -> str:
    succ, _w = transition_graph_mod2j(j)
    M = 1 << j
    lines: list[str] = []
    out = lines.append
    out("%% AUTO-GENERATED by paper/make_residue_graph_figure.py — do not edit.")
    out("%% True transition graph G_%d on Z/%dZ of the accelerated map T:" % (j, M))
    out("%% each residue r has the two successors T(r) mod %d and T(r+%d) mod %d."
        % (M, M, M))
    out("\\begin{tikzpicture}[")
    out("    >=stealth,")
    out("    every node/.style={circle, draw, inner sep=1.2pt, minimum size=6.4mm, font=\\small},")
    out("    oddnode/.style={fill=gray!20},")
    out("    fixnode/.style={fill=gray!45, very thick},")
    out("    oddarc/.style={->, semithick},")
    out("    evenarc/.style={->, densely dotted},")
    out("    looplab/.style={draw=none, fill=none, rectangle, inner sep=1pt, font=\\scriptsize},")
    out("    ]")
    # Nodes on a circle, residue 0 at the top, clockwise.
    for r in range(M):
        theta = 90.0 - 360.0 * r / M
        x = RADIUS_CM * math.cos(math.radians(theta))
        y = RADIUS_CM * math.sin(math.radians(theta))
        style = "fixnode" if r == M - 1 else ("oddnode" if r % 2 else "")
        opts = "[%s]" % style if style else ""
        out("  \\node%s (n%d) at (%.3f, %.3f) {$%d$};" % (opts, r, x, y, r))
    out("")
    # Arcs: style encodes the (parity-determined) weight of every arc
    # leaving r: log2(3) - 1 if r is odd, -1 if r is even.
    for r in range(M):
        style = "oddarc" if r % 2 else "evenarc"
        for s in succ[r]:
            if s == r:
                theta = 90.0 - 360.0 * r / M
                out("  \\draw[%s] (n%d) edge[out=%.1f, in=%.1f, looseness=14,"
                    " min distance=9mm] (n%d);" % (style, r, theta + 20, theta - 20, r))
            else:
                out("  \\draw[%s] (n%d) to[bend right=14] (n%d);" % (style, r, s))
    out("")
    # Label the two self-loops with their exact weights.
    out("  \\node[looplab, above=11.5mm of n0] {$-1$};")
    theta = 90.0 - 360.0 * (M - 1) / M
    out("  \\node[looplab] at (%.3f, %.3f) {$\\log_2 3 - 1$};"
        % ((RADIUS_CM + 1.55) * math.cos(math.radians(theta)),
           (RADIUS_CM + 1.55) * math.sin(math.radians(theta))))
    out("\\end{tikzpicture}")
    out("")
    return "\n".join(lines)


def main() -> None:
    j = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    path = os.path.join(os.path.dirname(__file__), "residue_graph_j%d.tex" % j)
    tex = tikz_residue_graph(j)
    with open(path, "w") as fh:
        fh.write(tex)
    print("wrote %s (%d nodes, %d arcs)" % (path, 1 << j, 2 * (1 << j)))


if __name__ == "__main__":
    main()
